# Generated by Django 5.2 on 2025-04-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Photo',
            new_name='photo',
        ),
    ]
