# Generated by Django 5.2 on 2025-04-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_doctor_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.patient'),
        ),
    ]
