# Generated by Django 5.2 on 2025-04-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_doctor_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='doctor',
        ),
        migrations.AddField(
            model_name='nurse',
            name='clinic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.clinic'),
            preserve_default=False,
        ),
    ]
